### PR TITLE
cleans up duplicate event_ids from heap

### PR DESCRIPTION
**Pull request by melissa-mg**
# New Pull Request

Check off the things that are applicable.  Some sections are mandetory for a review to continue.

Note: for the checkbox to format correctly, make sure there aren't any spaces between [ ]
- [x] completed task
- [ ] incomplete task

## What has changed?
- [ ] New Models
- [x] Updated Models
- [ ] Config Change

### What issue is this PR meant to fix?
I had an instance of two duplicate rows (same event_id) in the raw data from the heap events table

### Provide any context to assist the reviewer and a speedy PR turnaround:
This cleans that up so the heap_events model can pass its schema tests. Tested locally for gooten and it fixed the schema test failure.  

### Complexity
- [ ] Simple 1-liner, please rubber stamp
- [x] Simple model update.  I don't expect any issues
- [ ] Business rules.  Need another set of eyes.  I have provided detailed context and documentations on how rules are meant to function
- [ ] Massive re-write.  What have I done?

## Model Changes
All of the following exist:
- [x] Schema exist for the new/updated model
- [x] An appropriate unique test exists in schema

If the above is not applicable specify why:
- [ ] No model changes
- [ ] other:

## Development Process
I have done all:
- [x] `dbt run` locally
- [x] `dbt test` locally

or:
- [ ] It wasn't necessary because: 

*Note:  Pull Requests will not be reviewed otherwise*

### CODE REVIEW

**Review by Skorch — CHANGES_REQUESTED** [review]
Since this is a generic project can you convert to a cte + where filter ?  Not everyone is using snowflake.

**Comment by melissa-mg** [comment]
@Skorch updated to CTE

**Review by Skorch — APPROVED** [review]
you could also alternatively use the {{dbt_utils.star(source('heap', 'all_events'), exclude=["row_number"])}} in the final select.. but this looks good.

**Comment by melissa-mg** [comment]
oh nice that's super handy! I frequently want to select all but exclude one column and it's so tedious to list out all the columns

**Pull request merged**
